# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teste.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bteste.proto\x12\x05teste\"\x06\n\x04Nada\"2\n\x0fMatrizesRequest\x12\x1f\n\x08matrizes\x18\x01 \x03(\x0b\x32\r.teste.Matriz\"-\n\x06Matriz\x12\x10\n\x08\x64imencao\x18\x01 \x03(\x05\x12\x11\n\telementos\x18\x02 \x03(\x02\"/\n\x0eMatrizResposta\x12\x1d\n\x06result\x18\x01 \x01(\x0b\x32\r.teste.Matriz\"\x1d\n\x08LongList\x12\x11\n\tlistasoma\x18\x01 \x03(\x03\"\x14\n\x04Long\x12\x0c\n\x04long\x18\x01 \x01(\x03\"\x17\n\x06String\x12\r\n\x05valor\x18\x01 \x01(\t\"T\n\x05\x43\x61rro\x12\r\n\x05marca\x18\x01 \x01(\t\x12\x0e\n\x06modelo\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x0b\n\x03\x63or\x18\x04 \x01(\t\x12\x12\n\nvelocidade\x18\x05 \x01(\x05\x32\x86\x02\n\x07Service\x12#\n\x07method1\x12\x0b.teste.Nada\x1a\x0b.teste.Nada\x12#\n\x07method2\x12\x0b.teste.Long\x1a\x0b.teste.Long\x12\'\n\x07method3\x12\x0f.teste.LongList\x1a\x0b.teste.Long\x12\'\n\x07method4\x12\r.teste.String\x1a\r.teste.String\x12%\n\x07method5\x12\x0c.teste.Carro\x1a\x0c.teste.Carro\x12\x38\n\x07method6\x12\x16.teste.MatrizesRequest\x1a\x15.teste.MatrizRespostab\x06proto3')



_NADA = DESCRIPTOR.message_types_by_name['Nada']
_MATRIZESREQUEST = DESCRIPTOR.message_types_by_name['MatrizesRequest']
_MATRIZ = DESCRIPTOR.message_types_by_name['Matriz']
_MATRIZRESPOSTA = DESCRIPTOR.message_types_by_name['MatrizResposta']
_LONGLIST = DESCRIPTOR.message_types_by_name['LongList']
_LONG = DESCRIPTOR.message_types_by_name['Long']
_STRING = DESCRIPTOR.message_types_by_name['String']
_CARRO = DESCRIPTOR.message_types_by_name['Carro']
Nada = _reflection.GeneratedProtocolMessageType('Nada', (_message.Message,), {
  'DESCRIPTOR' : _NADA,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.Nada)
  })
_sym_db.RegisterMessage(Nada)

MatrizesRequest = _reflection.GeneratedProtocolMessageType('MatrizesRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATRIZESREQUEST,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.MatrizesRequest)
  })
_sym_db.RegisterMessage(MatrizesRequest)

Matriz = _reflection.GeneratedProtocolMessageType('Matriz', (_message.Message,), {
  'DESCRIPTOR' : _MATRIZ,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.Matriz)
  })
_sym_db.RegisterMessage(Matriz)

MatrizResposta = _reflection.GeneratedProtocolMessageType('MatrizResposta', (_message.Message,), {
  'DESCRIPTOR' : _MATRIZRESPOSTA,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.MatrizResposta)
  })
_sym_db.RegisterMessage(MatrizResposta)

LongList = _reflection.GeneratedProtocolMessageType('LongList', (_message.Message,), {
  'DESCRIPTOR' : _LONGLIST,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.LongList)
  })
_sym_db.RegisterMessage(LongList)

Long = _reflection.GeneratedProtocolMessageType('Long', (_message.Message,), {
  'DESCRIPTOR' : _LONG,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.Long)
  })
_sym_db.RegisterMessage(Long)

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), {
  'DESCRIPTOR' : _STRING,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.String)
  })
_sym_db.RegisterMessage(String)

Carro = _reflection.GeneratedProtocolMessageType('Carro', (_message.Message,), {
  'DESCRIPTOR' : _CARRO,
  '__module__' : 'teste_pb2'
  # @@protoc_insertion_point(class_scope:teste.Carro)
  })
_sym_db.RegisterMessage(Carro)

_SERVICE = DESCRIPTOR.services_by_name['Service']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NADA._serialized_start=22
  _NADA._serialized_end=28
  _MATRIZESREQUEST._serialized_start=30
  _MATRIZESREQUEST._serialized_end=80
  _MATRIZ._serialized_start=82
  _MATRIZ._serialized_end=127
  _MATRIZRESPOSTA._serialized_start=129
  _MATRIZRESPOSTA._serialized_end=176
  _LONGLIST._serialized_start=178
  _LONGLIST._serialized_end=207
  _LONG._serialized_start=209
  _LONG._serialized_end=229
  _STRING._serialized_start=231
  _STRING._serialized_end=254
  _CARRO._serialized_start=256
  _CARRO._serialized_end=340
  _SERVICE._serialized_start=343
  _SERVICE._serialized_end=605
# @@protoc_insertion_point(module_scope)
